### PR TITLE
migrated to libraries 2.0; documented support for 3rd gen devices

### PR DESCRIPTION
**Pull request by bsatrom**
I've tested this library with 3rd gen devices and the Adafruit MotorShield FeatherWing. This PR migrates the existing library to the Libraries 2.0 model and documented support for these devices.

### CODE REVIEW

**Comment by bsatrom** [comment]
Hi @Hypnopompia have you had a chance to review this PR?

**Comment by Hypnopompia** [comment]
Sorry this took so long to merge. I kept forgetting about it.

**Comment by bsatrom** [comment]
Thanks @Hypnopompia! Can you re-publish via the Particle CLI?

**Comment by Hypnopompia** [comment]
@bsatrom done!

**Pull request merged**
